---
name: CI

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

jobs:
  test:
    continue-on-error: true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['5.4', '5.5', '5.6', '7.0', '7.1', '7.2', '7.3', '7.4', '8.0', '8.1', '8.2', '8.3']

    steps:
      - uses: actions/checkout@v4
      - name: Set up PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          ini-values: include_path=.:/usr/share/php:pear/usr/share/php
          tools: none
      - name: Set up MySQL
        run: |
          sudo systemctl start mysql.service
          mysql -e 'CREATE DATABASE pear_db;' -uroot -proot
      - name: Set env
        run: |
          echo "MYSQL_TEST_USER=root" >> $GITHUB_ENV
          echo "MYSQL_TEST_PASSWD=root" >> $GITHUB_ENV
          echo "MYSQL_TEST_DB=pear_db" >> $GITHUB_ENV
          echo "MYSQL_TEST_HOST=127.0.0.1" >> $GITHUB_ENV
      - name: Run tests
        continue-on-error: true
        run: |
          pear run-tests -r tests/
      - name: Display results
        run: |
          for i in `find tests/ -name '*.out'`; do echo "$i"; cat "$i"; done